# docker-compose.yml

version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app # Your local frontend directory's contents are directly mirrored into the /app directory in the container.
      - /app/node_modules # To prevent the node_modules directory on your host from overwriting the node_modules directory inside the container
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '5001:5000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - '3310:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db-data:
